### ISSUE TITLE
Install plugin [Question]

### ISSUE THREAD

**Issue by luis9430** [Rodgath/Dilaz-Panel-Plugin#7]
Hello! I have a problem with the plugin, I followed the steps to install it add Dilaz-Panel-Options to my theme, I did the require configure the files, install this theme, but it still appears to me that the plugin is not installed 

![Untitled](https://user-images.githubusercontent.com/30971535/81533302-97ed2780-932b-11ea-8a19-bc50f52e74f8.png)

even install the n00b theme but that message also appears, I hope you can help me, thanks in advance

**Comment by Rodgath** [comment]
Hi, from the screenshot you shared, I can see you are using the latest version of the plugin. 

Have you renamed the plugin directory from 'dilaz-panel/dilaz-panel.php' to something else? 

Please let me know.

**Comment by Rodgath** [comment]
After some investigations, I have found out that the **Dilaz Panel Options** panel checks if **Dilaz Panel Plugin** is installed by using `is_plugin_active('dilaz-panel/dilaz-panel.php')`.

Please do not rename the **Dilaz Panel Plugin** path - '_wp-content/plugins/dilaz-panel/dilaz-panel.php_' to anything else because it is a requirement, in case there are any third party themes or plugins that will be using the Dilaz Panel Plugin. If its renamed, there may be conflicts. Also, the Dilaz Panel plugin automatic updater requires it's path to remain the same.

You can only rename the **Dilaz Panel Options** path to _anything_ you want because it is integrated into your project.
